### Coding Up the SVM

In [2]:
import sys
from class_vis import prettyPicture
from prep_terrain_data import makeTerrainData

import matplotlib.pyplot as plt
import copy
import numpy as np
import pylab as pl


features_train, labels_train, features_test, labels_test = makeTerrainData()


########################## SVM #################################
### we handle the import statement and SVC creation for you here
from sklearn.svm import SVC
clf = SVC(ker+nel="linear")


#### now your job is to fit the classifier
#### using the training features/labels, and to
#### make a set of predictions on the test data
clf.fit(features_train, labels_train)


#### store your predictions in a list named pred
pred = clf.predict(features_test)




from sklearn.metrics import accuracy_score
acc = accuracy_score(pred, labels_test)

def submitAccuracy():
    return acc

In [3]:
nx = np.array([[1,6], [2, 4], [3, 7], [4, 8], [7, 1], [8,4]])
nx

array([[1, 6],
       [2, 4],
       [3, 7],
       [4, 8],
       [7, 1],
       [8, 4]])

In [5]:
nq = np.array([[4, 2], ])
nq

array([[4, 2]])

In [6]:
np.sum(np.power(nx- nq, 2), axis= 1)

array([25,  8, 26, 36, 10, 20])

In [7]:
(8 + 10 + 20) / 3.0

12.666666666666666

In [8]:
np.sum(np.absolute(nx- nq), axis= 1)

array([7, 4, 6, 6, 4, 6])