In [3]:
import numpy as np 
a = np.array([[30,40,50,70],[80,20,70,10],[50,90,120,60]])  
print  '我们的数组是：'  
print a 
print  '\n'  
print  '调用 percentile() 函数：'  
print np.percentile(a,50)  
print  '\n'  
print  '沿轴 1 调用 percentile() 函数：'  
print np.percentile(a,50, axis =  1)  
print  '\n'  
print  '沿轴 0 调用 percentile() 函数：'  
print np.percentile(a,50, axis =  0)

我们的数组是：
[[ 30  40  50  70]
 [ 80  20  70  10]
 [ 50  90 120  60]]


调用 percentile() 函数：
55.0


沿轴 1 调用 percentile() 函数：
[ 45.  45.  75.]


沿轴 0 调用 percentile() 函数：
[ 50.  40.  70.  60.]


In [ ]:
a = np.array([[10, 7, 4], [3, 2, 1]])
>>> a
array([[10,  7,  4],
       [ 3,  2,  1]])
>>> np.percentile(a, 50)
3.5
>>> np.percentile(a, 50, axis=0)
array([[ 6.5,  4.5,  2.5]])
>>> np.percentile(a, 50, axis=1)
array([ 7.,  2.])
>>> np.percentile(a, 50, axis=1, keepdims=True)
array([[ 7.],
       [ 2.]])

In [4]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [5]:
np.percentile(a, 50)

3.5

In [7]:
x = np.array([1.3, 1.7, 2.4, 2.8, 3.5, 5.6, 6.6, 7.7, 8.8, 9.9])
x

array([ 1.3,  1.7,  2.4,  2.8,  3.5,  5.6,  6.6,  7.7,  8.8,  9.9])

In [11]:
x.sort()
x

array([ 1.3,  1.7,  2.4,  2.8,  3.5,  5.6,  6.6,  7.7,  8.8,  9.9])

In [8]:
np.percentile(x, 100)

9.9000000000000004

In [13]:
np.percentile(x, 90, interpolation= 'midpoint')

9.3500000000000014

In [14]:
np.percentile(x, 90, interpolation= 'linear')

8.9100000000000001

In [15]:
np.percentile(x, 90, interpolation= 'lower')

8.8000000000000007

In [16]:
np.percentile(x, 0)

1.3

In [17]:
np.percentile(x, 10)

1.6599999999999999

In [18]:
x = np.array([5 ,1 ,9 ,3 ,14, 9 ,7])
x

array([ 5,  1,  9,  3, 14,  9,  7])

In [22]:
np.percentile(x, 7.1,  interpolation= 'lower')

1

In [23]:
np.percentile(x, 35.7,  interpolation= 'lower')

5

In [29]:
list(range([1:11]))

SyntaxError: invalid syntax (<ipython-input-29-ed6686f71bac>, line 1)

In [39]:
x = np.array([15, 20, 35, 40, 50])
x

array([15, 20, 35, 40, 50])

In [50]:
np.percentile(x, 25, interpolation='midpoint')

20.0

In [38]:
np.__version__

'1.11.2'

In [51]:
a = np.array([[10, 7, 4], [3, 2, 1]])
a

array([[10,  7,  4],
       [ 3,  2,  1]])

In [52]:
np.percentile(a, 50)

3.5

In [56]:
adict = {'ab':10,'hg':11}
adict

{'ab': 10, 'hg': 11}

In [57]:
adict[0]

KeyError: 0